version: "2.1"

# volumes:
#   postgresql_12:

services:
  postgres:
    image: postgres:12
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5433:5432"
    volumes:
      - ./data/postgresql:/var/lib/postgresql
      - ./staging_files:/var/lib/postgresql/staging_files

  webserver:
    image: apache/airflow:latest
    hostname: webserver
    restart: always
    depends_on:
      - postgres
    env_file:
      - airflow.env
    volumes:
      - ./staging_files:/opt/airflow/staging_files
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./airflow-logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./variables:/opt/airflow/variables
    ports:
      - "8080:8080"
    # command: 'bash -c "airflow db init &&  airflow users create --username admin  --firstname Air --lastname Flow --role Admin --email airflow@airflow.com -p admin && airflow webserver -D && airflow scheduler -D"'
    entrypoint: ./scripts/airflow-entrypoint.sh
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 32

  # scheduler:
  #   image: apache/airflow:latest
  #   restart: always
  #   depends_on:
  #     - postgres
  #     - webserver
  #   env_file:
  #     - airflow.env
  #   ports:
  #     - "8793:8793"
  #   volumes:
  #     - ./dags:/opt/airflow/dags
  #     - ./plugins:/opt/airflow/plugins
  #     - ./airflow-logs:/opt/airflow/logs
  #     - ./scripts:/opt/airflow/scripts
  #     - ./variables:/opt/airflow/variables
  #   command: scheduler
  #   entrypoint: ./scripts/airflow-entrypoint.sh
  #   healthcheck:
  #     test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-scheduler.pid ]"]
  #     interval: 30s
  #     timeout: 30s
  #     retries: 3
  #

