version: "2.1"

# volumes:
#   postgresql_12:

services:
  postgres:
    image: postgres:12
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5433:5432"
    volumes:
      - ./data/postgresql:/var/lib/postgresql

  # airflow_db_init:
  #   image: apache/airflow:latest
  #   # build:
  #   #   context: ..
  #   #   dockerfile: docker/Dockerfile
  #   depends_on:
  #     - postgres
  #   volumes:
  #     #- ../airflow.cfg:/usr/local/airflow/airflow.cfg
  #     - ../variables:/usr/local/airflow/variables
  #   command:
  #     - /bin/bash
  #     - -c
  #     - |
  #       airflow db init
  #       if [[ -e /usr/local/airflow/variables/dev/all.json ]]; then
  #           airflow variables -i /usr/local/airflow/variables/dev/all.json
  #       fi
  #       # Enable this if you choose to have RBAC UI activated in the webserver
  #       airflow create_user -r admin -u airflow -e airflow@airflow.com -f Air -l Flow -p airflow
  #
  webserver:
    image: apache/airflow:latest
    hostname: webserver
    restart: always
    depends_on:
      - postgres
    env_file:
      - airflow.env
    volumes:
      - ./plugins:/opt/airflow/plugins
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./airflow-logs:/opt/airflow/logs
      - ./variables:/opt/airflow/variables
    ports:
      - "8080:8080"
    entrypoint: ./scripts/airflow-entrypoint.sh
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 32

  # scheduler:
  #   image: apache/airflow:latest
  #   restart: always
  #   depends_on:
  #     - postgres
  #     - webserver
  #   env_file:
  #     - airflow.env
  #   ports:
  #     - "8793:8793"
  #   volumes:
  #     - ./dags:/opt/airflow/dags
  #     - ./plugins:/opt/airflow/plugins
  #     - ./airflow-logs:/opt/airflow/logs
  #     - ./scripts:/opt/airflow/scripts
  #     - ./variables:/opt/airflow/variables
  #   command: scheduler
  #   entrypoint: ./scripts/airflow-entrypoint.sh
  #   healthcheck:
  #     test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-scheduler.pid ]"]
  #     interval: 30s
  #     timeout: 30s
  #     retries: 3
  #

