version: "2.1"

# volumes:
#   postgresql_12:

services:
  postgres:
    image: postgres:12
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
        # Host port=5433 because other Postgres is running on 5432
      - "5433:5432"
    volumes:
        # Mount to a local directory instead of a volume
      - ./data/postgresqli/data:/var/lib/postgresql/data

  webserver:
    image: apache/airflow:latest
    hostname: webserver
    restart: on-failure
    depends_on:
      - postgres
    environment:
      - POSTGRES_PASSWORD=airflow
    env_file:
      - airflow.env
    volumes:
      - ./staging_files:/opt/airflow/staging_files
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./airflow-logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./variables:/opt/airflow/variables
    ports:
      - "8080:8080"
    entrypoint: ["./scripts/wait-for-postgres.sh", "postgres", "./scripts/airflow-entrypoint.sh"]
    # entrypoint: ./scripts/airflow-entrypoint.sh
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 120s
      timeout: 30s
      retries: 32

  scheduler:
    image: apache/airflow:latest
    restart: on-failure
    depends_on:
      - postgres
      - webserver
    environment:
      - POSTGRES_PASSWORD=airflow
    env_file:
      - airflow.env
    ports:
      - "8793:8793"
    volumes:
      - ./staging_files:/opt/airflow/staging_files
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./airflow-logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./variables:/opt/airflow/variables
    entrypoint: ["./scripts/wait-for-postgres.sh", "postgres", "./scripts/start_airflow_scheduler.sh"]
    #entrypoint: ./scripts/start_airflow_scheduler.sh
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-scheduler.pid ]"]
      interval: 120s
      timeout: 30s
      retries: 3


