# Inspired by
# https://bhadrajatin.medium.com/docker-volume-mount-as-non-root-77ffae5a79d0
FROM  apache/airflow:latest

USER root
RUN mkdir ./staging_files && chown airflow:airflow ./staging_files

USER airflow
